fix ansible 1.9.x compatability code
Previously, setting self.basedir would fail if runner was None
Since evaluating self.runner.basedir would fail with:
    AttributeError: 'NoneType' object has no attribute 'basedir'

In addition to providing support for this being None, also respect the setting
of self.basedir directly from basedir, as a higher precedence. Previously any
passed arg for basedir was ignored.